### ISSUE TITLE
Go 1.17 B.Setenv() and T.Setenv()

### ISSUE THREAD

**Issue by bflad** [mitchellh/go-testing-interface#10]
## Description

[Go 1.17's](https://golang.org/doc/go1.17#testing) `testing` package now includes new [`B.Setenv()`](https://pkg.go.dev/testing#B.Setenv) and [`T.Setenv()`](https://pkg.go.dev/testing#T.Setenv) methods. These reset the existing environment variable value via `Cleanup()`. Panics when used with `Parallel()` (called either before or after) since it would cause conflicting testing environments.

**Comment by maoueh** [comment]
Are we missing the GitHub release `tag` for this new support?
